# Generated by Django 5.2.7 on 2025-10-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereviewcategory',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Critical Analysis'), (2, 'Technical Breakdown')], null=True),
        ),
    ]
