# Generated by Django 5.2.7 on 2025-10-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
        ('movies', '0002_movie_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieCountry',
        ),
        migrations.DeleteModel(
            name='MovieDirector',
        ),
        migrations.DeleteModel(
            name='MovieGenre',
        ),
        migrations.DeleteModel(
            name='MovieLanguage',
        ),
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(blank=True, to='metadata.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ManyToManyField(blank=True, to='metadata.creator'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, to='metadata.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ManyToManyField(blank=True, to='metadata.language'),
        ),
    ]
