# Generated by Django 5.2.7 on 2025-10-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviereviewcategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereviewcategory',
            name='icon_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
