# Generated by Django 5.2.7 on 2025-10-28 07:00

import django.db.models.deletion
import reviewapp.core.utils
import thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('photo', thumbnails.fields.ImageField(blank=True, null=True, upload_to=reviewapp.core.utils.FilenameGenerator(prefix='author_photos'))),
            ],
            options={
                'verbose_name': 'Book Author',
                'verbose_name_plural': 'Book Authors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Book Category',
                'verbose_name_plural': 'Book Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('suggested_for', models.PositiveSmallIntegerField(choices=[(1, 'All Genres'), (2, 'Fiction'), (3, 'Non-Fiction'), (4, 'Academic'), (5, 'Self-Help'), (6, 'History'), (7, 'Religious'), (8, 'Science'), (9, 'Biography'), (10, 'Technical')], default='ALL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('image', thumbnails.fields.ImageField(blank=True, null=True, upload_to=reviewapp.core.utils.FilenameGenerator(prefix='book_images'))),
                ('publisher', models.CharField(blank=True, max_length=100)),
                ('publication_year', models.PositiveIntegerField()),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, default='English', max_length=50)),
                ('authors', models.ManyToManyField(blank=True, to='books.bookauthor')),
                ('category', models.ManyToManyField(blank=True, to='books.bookcategory')),
            ],
            options={
                'ordering': ['-publication_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.FloatField()),
                ('goodreads_rating', models.FloatField(blank=True, null=True)),
                ('amazon_rating', models.FloatField(blank=True, null=True)),
                ('review_summary', models.TextField(blank=True, help_text='Brief summary of the review', null=True)),
                ('detailed_review', models.TextField(help_text='Full detailed review')),
                ('personal_reflection', models.TextField(blank=True, help_text='Personal thoughts and reflections')),
                ('final_verdict', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Book Review',
                'verbose_name_plural': 'Book Reviews',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('quote_title', models.CharField(blank=True, max_length=200, null=True)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='books.bookreview')),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.reviewsectiontype')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_year'], name='books_book_publica_75adf4_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['book', 'created'], name='books_bookr_book_id_84140e_idx'),
        ),
        migrations.AddIndex(
            model_name='bookreview',
            index=models.Index(fields=['overall_rating'], name='books_bookr_overall_38f1c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookreview',
            unique_together={('book', 'created_by')},
        ),
    ]
