# Generated by Django 5.2.7 on 2025-10-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAuthor',
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.ManyToManyField(blank=True, to='metadata.country'),
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='metadata.creator'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, to='metadata.genre'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(blank=True, to='metadata.language'),
        ),
    ]
